# PostgreSQL Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Production Logging
spring.jpa.show-sql=false

# File Storage
app.upload-dir=/opt/constructiq/uploads

# Redis Cache
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

app.cors.allowed-origins=https://constructiq.com,https://www.constructiq.com
